<a href="https://colab.research.google.com/github/FaizalRahman-ai/Project1/blob/main/Intro%20to%20Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Setup Tensorflow
import tensorflow as tf
print("Tensorflow version:", tf.__version__)

Tensorflow version: 2.17.1


In [3]:
#load a Dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/ 255.0, x_test/ 255.0

11490434/11490434 ━━━━━━━━━━━━━━━━━━━━ 0s 0us/step


In [4]:
#Building a Machine learning Model
#Building a tf.keras.Sequential Model
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation= 'relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [5]:
#predictions
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.32228878,  0.3353681 , -0.12620041,  0.2083247 ,  0.5117047 ,
        -0.08068578,  0.13971895,  1.0169681 , -0.89594656, -0.24334225]],
      dtype=float32)

In [6]:
#tf.nn.softmax converts these logits into probablities of each class
tf.nn.softmax(predictions).numpy()

array([[0.10963871, 0.11108211, 0.07001442, 0.09782952, 0.13250314,
        0.07327475, 0.09134291, 0.21961364, 0.03242582, 0.06227496]],
      dtype=float32)

In [9]:
#Defining a loss function for training using losses.sparseCategoricalcrossentropy
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits="True")
loss_fn(y_train[:1], predictions).numpy()

2.6135392

In [10]:
#Before Training we need to configure & compile the model using model.keras & setting optimizer to "adam"
model.compile(optimizer="adam",
              loss=loss_fn,
              metrics=["accuracy"])

In [11]:
#Train & evaluate the model using model.fit()
model.fit(x_train, y_train, epochs=10)


Epoch 1/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 4ms/step - accuracy: 0.8561 - loss: 0.4804
Epoch 2/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - accuracy: 0.9566 - loss: 0.1522
Epoch 3/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - accuracy: 0.9682 - loss: 0.1041
Epoch 4/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9745 - loss: 0.0855
Epoch 5/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9762 - loss: 0.0742
Epoch 6/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - accuracy: 0.9787 - loss: 0.0665
Epoch 7/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9810 - loss: 0.0548
Epoch 8/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - accuracy: 0.9844 - loss: 0.0479
Epoch 9/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - accuracy: 0.9846 - loss: 0.0455
Epoch 10/10
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 12s 4ms/step - accuracy: 0.9864 - loss: 0.0419


In [12]:
#The Model.evaluate method checks the model's performance, usually on a validation set or test set.
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9786 - loss: 0.0673


[0.0672570988535881, 0.978600025177002]

In [14]:
#If we want our model to return a probability, you can wrap the trained model, and attach the softmax to it:
probablity_model = tf.keras.Sequential([
               model,
               tf.keras.layers.Softmax()
               ])
probablity_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.56544438e-12, 5.13229285e-11, 2.00124628e-08, 4.77769845e-06,
        2.76085036e-14, 1.09902865e-10, 5.66094883e-16, 9.99995232e-01,
        2.73100292e-10, 1.75846697e-08],
       [9.43826649e-07, 3.70847483e-05, 9.99961972e-01, 4.26519087e-08,
        4.00692549e-21, 3.24764526e-09, 1.07146647e-09, 1.48487205e-15,
        6.59031008e-09, 2.71052288e-14],
       [1.32626032e-09, 9.99744475e-01, 1.05479667e-05, 5.91472599e-07,
        7.02471482e-07, 2.31713120e-08, 2.13063451e-08, 1.52689725e-04,
        9.08397487e-05, 5.90309170e-08],
       [9.99960303e-01, 1.49686538e-13, 3.93725804e-06, 1.41354732e-07,
        6.29291064e-09, 1.86587731e-05, 3.09183361e-06, 9.85592337e-08,
        2.25916508e-11, 1.36697445e-05],
       [8.48887627e-09, 2.01214414e-12, 2.51052825e-07, 1.65143554e-09,
        9.99778450e-01, 2.78822387e-09, 7.22468485e-09, 8.25282132e-06,
        1.00529292e-08, 2.13074192e-04]], dtype=float32)>